### ISSUE TITLE
Fails to run on FreeBSD or other BSD based platforms.

### ISSUE THREAD

**Issue by busbyjon** [ehendrix23/tesla_dashcam#106]
The current build (0.16) currently fails on FreeBSD based platforms (FreeNAS here), as there are no settings for this OS (such as "MOVIE_FOLDER").

Suggest moving to this a linux/non-linux based switch at somepoint in the future

Traceback (most recent call last):
  File "/usr/local/bin/tesla_dashcam", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/tesla_dashcam/tesla_dashcam.py",line 2144, in main
    movie_folder = os.path.join(str(Path.home()), MOVIE_HOMEDIR.get(sys.platform), "")
  File "/usr/local/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/local/lib/python3.7/genericpath.py", line 153, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'

**Comment by ehendrix23** [comment]
New version has a fix allowing it to run on FreeBSD 11
