### ISSUE TITLE
Bug in 1.9 Beta

### ISSUE THREAD

**Issue by supercazzola** [ehendrix23/tesla_dashcam#12]
./tesla_dashcam /Volumes/TESLA/TeslaCam/
New release v0.1.8 is available for download (https://github.com/ehendrix23/tesla_dashcam/releases/tag/v0.1.8). You are currently on v0.1.9b0. Use --check-for-update to get latest release notes.
GPU acceleration is enabled
Discovered 1 folders with 2 clips to process.
	Processing 2 clips in folder /Volumes/TESLA/TeslaCam/RecentClips (1/1)
		Processing clip 1/2 from 04/21/19 18:37:22 and 27 seconds long.
Traceback (most recent call last):
  File "tesla_dashcam/tesla_dashcam.py", line 1444, in <module>
  File "tesla_dashcam/tesla_dashcam.py", line 1440, in main
  File "tesla_dashcam/tesla_dashcam.py", line 716, in process_folders
  File "tesla_dashcam/tesla_dashcam.py", line 448, in create_intermediate_movie
UnboundLocalError: local variable 'camera_1' referenced before assignment
[19838] Failed to execute script tesla_dashcam
Trenzalore-2:tesla_dashcam_19beta spoo$

**Comment by geirgp** [comment]
I get the same error

**Comment by ehendrix23** [comment]
Fixed in new beta: https://github.com/ehendrix23/tesla_dashcam/releases/tag/v0.1.9b1
