### ISSUE TITLE
FileNotFoundError in MagicalYak's updated docker image

### ISSUE THREAD

**Issue by 3rdStng** [ehendrix23/tesla_dashcam#181]
I upgraded my docker image using the recent update by @magicalyak to version 0.1.19 and now when I put some older test sentry clips into the proper directory, Tesla_dashcam sees the trigger file, but then gives errors from the python script and crashes the docker.

```
Monitoring for trigger /root/Import/SentryClips/ARCHIVE_UPLOADED to exist. Press CTRL-C to stop
Trigger /root/Import/SentryClips/ARCHIVE_UPLOADED exist.
Retrieving all files from:
/root/Import/SentryClips/source
/root/Import/SavedClips
/root/Import/SentryClips/source
/root/Import/SentryClips
Scanning 3 folder(s)
Traceback (most recent call last):
File "/usr/src/app/tesla_dashcam/tesla_dashcam/tesla_dashcam.py", line 4502, in <module>
sys.exit(main())
File "/usr/src/app/tesla_dashcam/tesla_dashcam/tesla_dashcam.py", line 4426, in main
process_folders(source_folder_list, video_settings, args.delete_source)
File "/usr/src/app/tesla_dashcam/tesla_dashcam/tesla_dashcam.py", line 2568, in process_folders
event_list = get_movie_files(source_folders, video_settings)
File "/usr/src/app/tesla_dashcam/tesla_dashcam/tesla_dashcam.py", line 1451, in get_movie_files
metadata = get_metadata(
File "/usr/src/app/tesla_dashcam/tesla_dashcam/tesla_dashcam.py", line 1669, in get_metadata
command_result = run(ffmpeg_command, capture_output=True, text=True)
File "/usr/local/lib/python3.10/subprocess.py", line 501, in run
with Popen(*popenargs, **kwargs) as process:
File "/usr/local/lib/python3.10/subprocess.py", line 966, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "/usr/local/lib/python3.10/subprocess.py", line 1842, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
```

_Originally posted by @3rdStng in https://github.com/ehendrix23/tesla_dashcam/issues/96#issuecomment-939186682_

**Comment by magicalyak** [comment]
I’ll take a look this weekend

**Comment by magicalyak** [comment]
Can you try the latest?

**Comment by magicalyak** [comment]
magicalyak/tesla_dashcam:latest

**Comment by 3rdStng** [comment]
The docker didn't crash, which is good. But due to my --delete_source flag, it only nuked the video folders and didn't process/create any video.

```
Monitoring for trigger /root/Import/SentryClips/ARCHIVE_UPLOADED to exist. Press CTRL-C to stop
Trigger /root/Import/SentryClips/ARCHIVE_UPLOADED exist.
Retrieving all files from:
/root/Import/SentryClips/source
/root/Import/SavedClips
/root/Import/SentryClips/source
/root/Import/SentryClips
Scanning 4 folder(s)
There are 2 event folder(s) with 16 clips to process.
Processing 8 clips in folder /root/Import/SentryClips/2021-09-27_16-24-42 (1/2)
Creating movie /root/Videos/Tesla_Dashcam/2021-09-27T16-16-27_2021-09-27T16-23-29.mp4, please be patient.
Error: No valid clips to merge found.

Deleting 34 files and folder /root/Import/SentryClips/2021-09-27_16-24-42
Processing 8 clips in folder /root/Import/SentryClips/2021-10-08_18-41-18 (2/2)
Creating movie /root/Videos/Tesla_Dashcam/2021-10-08T18-34-11_2021-10-08T18-40-46.mp4, please be patient.
Error: No valid clips to merge found.

Deleting 34 files and folder /root/Import/SentryClips/2021-10-08_18-41-18
No clips found.
Total processing time: 0:00:00
2 folders with 16 clips have been processed, /root/Videos/Tesla_Dashcam contains resulting files.

Processing of movies has completed.
Monitoring for trigger /root/Import/SentryClips/ARCHIVE_UPLOADED. Press CTRL-C to stop
```

**Comment by magicalyak** [comment]
Let’s start a new issue on this.
