### ISSUE TITLE
Can't change the scale of clips

### ISSUE THREAD

**Issue by Jarky0** [ehendrix23/tesla_dashcam#191]
I would like to have the full resoltution of all 4 clips. But I can't even change the scale of one clip.

I get the following error:
```
C:\Users\USER\Desktop\tesla_dashcam>tesla_dashcam.exe --scale 1 "D:\teslacam\SavedClips\2021-12-14_16-25-13"
Traceback (most recent call last):
  File "\\vmware-host\Shared Folders\tesla_dashcam\tesla_dashcam\tesla_dashcam.py", line 4613, in <module>
  File "\\vmware-host\Shared Folders\tesla_dashcam\tesla_dashcam\tesla_dashcam.py", line 3928, in main
  File "\\vmware-host\Shared Folders\tesla_dashcam\tesla_dashcam\tesla_dashcam.py", line 839, in scale
  File "\\vmware-host\Shared Folders\tesla_dashcam\tesla_dashcam\tesla_dashcam.py", line 745, in scale
ValueError: could not convert string to float: 'd:\\teslacam\\savedclips\\2021-12-14_16-25-13'
[19648] Failed to execute script 'tesla_dashcam' due to unhandled exception!
```

I get the same Error in Linux.

**Comment by ehendrix23** [comment]
For now as a work-around, add another option after scale. For example:
```tesla_dashcam.exe --scale 1 --loglevel INFO "D:\teslacam\SavedClips\2021-12-14_16-25-13"```

Looks like it is interpreting the path as another option for scale. Adding log level INFO in theory doesn't change anything as INFO is the default log level.

**Comment by ehendrix23** [comment]
This should work with 0.1.21
