### ISSUE TITLE
 title_screen_map not working

### ISSUE THREAD

**Issue by MarcFinns** [ehendrix23/tesla_dashcam#198]
Hello, i tried to use the option but I do not get any map in the videos.
Is there any other setup needed? (e.g. where to download the map from..?)
thanks!

**Comment by ehendrix23** [comment]
It should work. No other setup is required.

Can you run it with debug enabled and then provide the output here together with your complete command (including parameters)?

Thx.

**Comment by rmyadsk** [comment]
I can confirm this --title_screen_map is failing for me as well:

> Scanning 23 folder(s)
Scanned 10/23.
Scanned 20/23.
There are 20 event folder(s) with 86 clips to process.
	Processing 7 clips in folder /Volumes/Samsung/tesla/SavedClips/2023-09-04_13-31-16 (1/20)
		Processing clip 1/7 from 09/04/23 13:25:05 and 59 seconds long.
		Processing clip 2/7 from 09/04/23 13:26:04 and 60 seconds long.
		Processing clip 3/7 from 09/04/23 13:27:04 and 59 seconds long.
		Processing clip 4/7 from 09/04/23 13:28:05 and 59 seconds long.
		Processing clip 5/7 from 09/04/23 13:29:05 and 59 seconds long.
		Processing clip 6/7 from 09/04/23 13:30:05 and 60 seconds long.
		Processing clip 7/7 from 09/04/23 13:31:06 and 0 seconds long.
		Creating movie /Volumes/Samsung/product/2023-09-04T13-25-04_2023-09-04T13-31-06.mp4, please be patient.
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37608/50044.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37608/50045.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37608/50046.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37608/50047.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37608/50048.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37609/50044.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37609/50045.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37609/50046.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37609/50047.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37609/50048.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37610/50044.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37610/50045.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37610/50046.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37610/50047.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37610/50048.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37611/50044.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37611/50045.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37611/50046.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37611/50047.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37611/50048.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37612/50044.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37612/50045.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37612/50046.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37612/50047.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37612/50048.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37613/50044.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37613/50045.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37613/50046.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37613/50047.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37613/50048.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37614/50044.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37614/50045.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37614/50046.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37614/50047.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37614/50048.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37615/50044.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37615/50045.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37615/50046.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37615/50047.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37615/50048.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37616/50044.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37616/50045.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37616/50046.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37616/50047.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37616/50048.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37608/50044.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37608/50045.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37608/50046.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37608/50047.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37608/50048.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37609/50044.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37609/50045.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37609/50046.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37609/50047.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37609/50048.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37610/50044.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37610/50045.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37610/50046.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37610/50047.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37610/50048.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37611/50044.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37611/50045.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37611/50046.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37611/50047.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37611/50048.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37612/50044.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37612/50045.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37612/50046.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37612/50047.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37612/50048.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37613/50044.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37613/50045.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37613/50046.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37613/50047.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37613/50048.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37614/50044.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37614/50045.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37614/50046.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37614/50047.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37614/50048.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37615/50044.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37615/50045.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37615/50046.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37615/50047.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37615/50048.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37616/50044.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37616/50045.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37616/50046.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37616/50047.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37616/50048.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37608/50044.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37608/50045.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37608/50046.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37608/50047.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37608/50048.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37609/50044.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37609/50045.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37609/50046.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37609/50047.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37609/50048.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37610/50044.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37610/50045.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37610/50046.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37610/50047.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37610/50048.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37611/50044.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37611/50045.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37611/50046.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37611/50047.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37611/50048.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37612/50044.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37612/50045.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37612/50046.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37612/50047.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37612/50048.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37613/50044.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37613/50045.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37613/50046.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37613/50047.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37613/50048.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37614/50044.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37614/50045.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37614/50046.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37614/50047.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37614/50048.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37615/50044.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37615/50045.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37615/50046.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37615/50047.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37615/50048.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37616/50044.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37616/50045.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37616/50046.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37616/50047.png
request failed [404]: http://a.tile.komoot.de/komoot-2/17/37616/50048.png
Traceback (most recent call last):
  File "tesla_dashcam/tesla_dashcam.py", line 4613, in <module>
  File "tesla_dashcam/tesla_dashcam.py", line 4601, in main
  File "tesla_dashcam/tesla_dashcam.py", line 2841, in process_folders
  File "tesla_dashcam/tesla_dashcam.py", line 2179, in create_movie
  File "tesla_dashcam/tesla_dashcam.py", line 2163, in create_title_screen
  File "staticmap/staticmap.py", line 285, in render
  File "staticmap/staticmap.py", line 412, in _draw_base_layer
RuntimeError: could not download 45 tiles: [(37608, 50044, 'http://a.tile.komoot.de/komoot-2/17/37608/50044.png'), (37608, 50045, 'http://a.tile.komoot.de/komoot-2/17/37608/50045.png'), (37608, 50046, 'http://a.tile.komoot.de/komoot-2/17/37608/50046.png'), (37608, 50047, 'http://a.tile.komoot.de/komoot-2/17/37608/50047.png'), (37608, 50048, 'http://a.tile.komoot.de/komoot-2/17/37608/50048.png'), (37609, 50044, 'http://a.tile.komoot.de/komoot-2/17/37609/50044.png'), (37609, 50045, 'http://a.tile.komoot.de/komoot-2/17/37609/50045.png'), (37609, 50046, 'http://a.tile.komoot.de/komoot-2/17/37609/50046.png'), (37609, 50047, 'http://a.tile.komoot.de/komoot-2/17/37609/50047.png'), (37609, 50048, 'http://a.tile.komoot.de/komoot-2/17/37609/50048.png'), (37610, 50044, 'http://a.tile.komoot.de/komoot-2/17/37610/50044.png'), (37610, 50045, 'http://a.tile.komoot.de/komoot-2/17/37610/50045.png'), (37610, 50046, 'http://a.tile.komoot.de/komoot-2/17/37610/50046.png'), (37610, 50047, 'http://a.tile.komoot.de/komoot-2/17/37610/50047.png'), (37610, 50048, 'http://a.tile.komoot.de/komoot-2/17/37610/50048.png'), (37611, 50044, 'http://a.tile.komoot.de/komoot-2/17/37611/50044.png'), (37611, 50045, 'http://a.tile.komoot.de/komoot-2/17/37611/50045.png'), (37611, 50046, 'http://a.tile.komoot.de/komoot-2/17/37611/50046.png'), (37611, 50047, 'http://a.tile.komoot.de/komoot-2/17/37611/50047.png'), (37611, 50048, 'http://a.tile.komoot.de/komoot-2/17/37611/50048.png'), (37612, 50044, 'http://a.tile.komoot.de/komoot-2/17/37612/50044.png'), (37612, 50045, 'http://a.tile.komoot.de/komoot-2/17/37612/50045.png'), (37612, 50046, 'http://a.tile.komoot.de/komoot-2/17/37612/50046.png'), (37612, 50047, 'http://a.tile.komoot.de/komoot-2/17/37612/50047.png'), (37612, 50048, 'http://a.tile.komoot.de/komoot-2/17/37612/50048.png'), (37613, 50044, 'http://a.tile.komoot.de/komoot-2/17/37613/50044.png'), (37613, 50045, 'http://a.tile.komoot.de/komoot-2/17/37613/50045.png'), (37613, 50046, 'http://a.tile.komoot.de/komoot-2/17/37613/50046.png'), (37613, 50047, 'http://a.tile.komoot.de/komoot-2/17/37613/50047.png'), (37613, 50048, 'http://a.tile.komoot.de/komoot-2/17/37613/50048.png'), (37614, 50044, 'http://a.tile.komoot.de/komoot-2/17/37614/50044.png'), (37614, 50045, 'http://a.tile.komoot.de/komoot-2/17/37614/50045.png'), (37614, 50046, 'http://a.tile.komoot.de/komoot-2/17/37614/50046.png'), (37614, 50047, 'http://a.tile.komoot.de/komoot-2/17/37614/50047.png'), (37614, 50048, 'http://a.tile.komoot.de/komoot-2/17/37614/50048.png'), (37615, 50044, 'http://a.tile.komoot.de/komoot-2/17/37615/50044.png'), (37615, 50045, 'http://a.tile.komoot.de/komoot-2/17/37615/50045.png'), (37615, 50046, 'http://a.tile.komoot.de/komoot-2/17/37615/50046.png'), (37615, 50047, 'http://a.tile.komoot.de/komoot-2/17/37615/50047.png'), (37615, 50048, 'http://a.tile.komoot.de/komoot-2/17/37615/50048.png'), (37616, 50044, 'http://a.tile.komoot.de/komoot-2/17/37616/50044.png'), (37616, 50045, 'http://a.tile.komoot.de/komoot-2/17/37616/50045.png'), (37616, 50046, 'http://a.tile.komoot.de/komoot-2/17/37616/50046.png'), (37616, 50047, 'http://a.tile.komoot.de/komoot-2/17/37616/50047.png'), (37616, 50048, 'http://a.tile.komoot.de/komoot-2/17/37616/50048.png')]
[79942] Failed to execute script 'tesla_dashcam' due to unhandled exception!

Going to one of the mentioned URLs in a browser results in a certificate error. Bypassing that, the text "Sorry [sic]cant find that!" is displayed.

**Comment by rmyadsk** [comment]
Ibid. 
![Screenshot 2023-09-21 at 05 00 22](https://github.com/ehendrix23/tesla_dashcam/assets/820865/c652f228-fd5a-4ec4-a2a2-bc9432714f4e)

**Comment by SimonKagstrom** [comment]
Probably that was a temporary issue for staticmap? The videos I generated today with --title_screen_map had the map generated fine.

**Comment by ehendrix23** [comment]
This might have been a temporary issue, I did not see any issues during my testing with 0.1.21
