### ISSUE TITLE
Issue when using tesla_dashcam from pip (macOS 10.14.5)

### ISSUE THREAD

**Issue by dburkland** [ehendrix23/tesla_dashcam#38]
When I install tesla_dashcam via pip3 (python 3.7.3 installed via homebrew) I get the following error any I time I try to execute it (no matter the arguments and/or source directory):

$ tesla_dashcam --quality LOWER --layout PERSPECTIVE --compression ultrafast --encoding x264 --output 201905_3_video_perspective_lower.mp4 201905_3/
GPU acceleration is enabled
Traceback (most recent call last):
  File "/usr/local/bin/tesla_dashcam", line 6, in <module>
    from tesla_dashcam.tesla_dashcam import main
  File "/usr/local/lib/python3.7/site-packages/tesla_dashcam/tesla_dashcam.py", line 2251, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/tesla_dashcam/tesla_dashcam.py", line 2109, in main
    os.mkdir(target_folder)
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by ehendrix23** [comment]
Release 0.1.11 has just been released fixing this issue
