### ISSUE TITLE
linux issue

### ISSUE THREAD

**Issue by j450h1** [ehendrix23/tesla_dashcam#39]
```python3 "tesla_dashcam/tesla_dashcam/tesla_dashcam.py"```

```
Traceback (most recent call last):
  File "tesla_dashcam/tesla_dashcam/tesla_dashcam.py", line 2251, in <module>
    sys.exit(main())
  File "tesla_dashcam/tesla_dashcam/tesla_dashcam.py", line 1441, in main
    ffmpeg_default = resource_path(FFMPEG.get(sys.platform, 'ffmpeg'))
  File "tesla_dashcam/tesla_dashcam/tesla_dashcam.py", line 1374, in resource_path
    return os.path.join(base_path, relative_path)
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'PosixPath'
```

**Comment by ehendrix23** [comment]
Release 0.1.11 should fix this issue.
