### ISSUE TITLE
Unexpected keyword argument 'capture_output'

### ISSUE THREAD

**Issue by a3020** [ehendrix23/tesla_dashcam#61]
Hi! Thanks for this great open-source repository. I'm having a play with it on a ubuntu machine. I installed ffmpeg and created a virtual environment for Python. Then installed the requirements and ran the tool with `venv/bin/python3.6 tesla_dashcam/tesla_dashcam.py /path/to/pics`.

That results in an error, both on the master branch as the latest release branch.

Stacktrace:

```
Discovered 2 folders containing total of 10 files, retrieving clip data.
Traceback (most recent call last):
  File "tesla_dashcam/tesla_dashcam.py", line 2518, in <module>
    sys.exit(main())
  File "tesla_dashcam/tesla_dashcam.py", line 2513, in main
    video_settings["source_folder"], args.exclude_subdirs, video_settings
  File "tesla_dashcam/tesla_dashcam.py", line 697, in get_movie_files
    video_settings["ffmpeg_exec"], [front_path, left_path, right_path]
  File "tesla_dashcam/tesla_dashcam.py", line 792, in get_metadata
    command_result = run(ffmpeg_command, capture_output=True, text=True)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

Any idea what's causing this?

**Comment by a3020** [comment]
I got it working with `venv` after also installing `python3.7-dev`, without it I couldn't install the dependencies. Thanks for your help and quick reply @ehendrix23. :clap:
