### ISSUE TITLE
time data does not match format '%Y-%m-%dT%H:%M:%S.%f%z'

### ISSUE THREAD

**Issue by magicalyak** [ehendrix23/tesla_dashcam#95]
I am getting the following error when running on python 3.7 on centos7
It looks like it is getting the date format incorrect

I am able to work around this by changing line 1311 in /usr/local/lib/python3.7/site-packages/tesla_dashcam/tesla_dashcam.py
to
`                line_split[1].strip(), "%Y-%m-%d %H:%M:%S"`
but it's a really hacky solution

```
[root@rocky tesla]# tesla_dashcam --merge --chapter_offset -30 --quality MEDIUM  --output /mnt2/tesla_dashcam/2019-10-06.mp4 /mnt2/tesla/2019-10-06/2019-10-06_15-23-12/
Discovered 1 folders containing total of 44 files in /mnt2/tesla/2019-10-06/2019-10-06_15-23-12/
Traceback (most recent call last):
  File "/usr/local/bin/tesla_dashcam", line 5, in <module>
    from tesla_dashcam import main
  File "/usr/local/lib/python3.7/site-packages/tesla_dashcam/__init__.py", line 1, in <module>
    from .tesla_dashcam import main
  File "/usr/local/lib/python3.7/site-packages/tesla_dashcam/tesla_dashcam.py", line 3431, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/tesla_dashcam/tesla_dashcam.py", line 3411, in main
    video_settings["source_folder"], args.exclude_subdirs, video_settings
  File "/usr/local/lib/python3.7/site-packages/tesla_dashcam/tesla_dashcam.py", line 1161, in get_movie_files
    [front_path, left_path, right_path, rear_path],
  File "/usr/local/lib/python3.7/site-packages/tesla_dashcam/tesla_dashcam.py", line 1311, in get_metadata
    line_split[1].strip(), "%Y-%m-%dT%H:%M:%S.%f%z"
  File "/usr/local/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '2019-10-06 19:12:18' does not match format '%Y-%m-%dT%H:%M:%S.%f%z'
```

**Comment by ehendrix23** [comment]
Download a newer version of ffmpeg. Same issue was reported earlier (Issue #93) and was resolved by updating ffmpeg from 2.8.15 to 4.x.
2.8.15 is now a very old version BTW.

**Comment by magicalyak** [comment]
Wow didn't expect that fast of a response.  Going to update now.   not to derail this but is there any other documentation on using the docker container?  I'll post results shortly on the ffmpeg upgrade

**Comment by magicalyak** [comment]
This is definitely my fault, updating the ffmpeg fixed it.  Not sure how I missed the other issue already opened.  Thank you.

**Comment by ehendrix23** [comment]
> Wow didn't expect that fast of a response. Going to update now. not to derail this but is there any other documentation on using the docker container? I'll post results shortly on the ffmpeg upgrade

Sorry no, someone provided that to me to make it easy to have with Docker container but I have never used it or so.
